version: "3.0"
services:
    reverse-proxy:
        image: traefik:v2.9
        # Enables the web UI and tells Traefik to listen to docker
        command: --api.insecure=true --providers.docker
        ports:
          # Static HTTP port
          - "80:80"
          # Traefik web interface
          - "8080:8080"
        volumes:
          # Ability to listen docker evenets
          - /var/run/docker.sock:/var/run/docker.sock
    appache:
        build: ./http-static
        ports:
            - "80"
        labels: 
            - "traefik.http.routers.static.rule=Host(`localhost`)"
        deploy:
            replicas: 2
    nodejs:
        build: ./http-dynamic
        ports:
            - "3000"
        labels: 
            - "traefik.http.routers.dynamic.rule=(Host(`localhost`) && PathPrefix(`/api`))"
        deploy:
            replicas: 3